### ISSUE TITLE
Tabular '1' doesn't match with proportional '1' in all romans

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#22]

**Comment by thisisdano** [comment]
Thanks for bringing this up — let me check up on it and I'll follow up later today

**Comment by thisisdano** [comment]
Can you tell me more about this? What do you expect and what do you see?

**Comment by cssobral2013** [comment]
Mr Williams, the top part of '1.tf' is still reminiscent of 18Franklin and wasn't updated to match the top part of '1'.

**Comment by cssobral2013** [comment]
Sorry to referring to you so courtesly - I'm unable to type 'at' in this keyboard.

**Comment by thisisdano** [comment]
This one actually is intentional. I was trying to draw a monospaced `1` that occupied more space. So it has that really extended base. It needed the top to balance the bottom and a long horizontal bar at the top looked unusual — a bit reedy. I figured that it was better to change its style than try to push the proportional `1`s design to a place it couldn't support. But maybe it's just too different?

**Comment by cssobral2013** [comment]
It's okay, then.

**Comment by thisisdano** [comment]
Thanks for asking
